base:
  gpu_id: '2'
  algorithm: DB
  pretrained: True
  in_channels: [24, 40, 48, 96]
  inner_channels: 96
  k: 50
  adaptive: True
  crop_shape: [640,640]
  shrink_ratio: 0.4
  n_epoch: 400
  start_val: 500
  show_step: 20
  checkpoints: ./checkpoint
  save_epoch: 1
  restore: False
  restore_file : ./checkpoint/ag_DB_bb_mobilenet_v3_small_he_DB_Head_bs_16_ep_400/DB_35.pth.tar

backbone:
  function: ptocr.model.backbone.det_mobilev3,mobilenet_v3_small

head:
  function: ptocr.model.head.det_DBHead,DB_Head
#  function: ptocr.model.head.det_FPEM_FFM_Head,FPEM_FFM_Head
#  function: ptocr.model.head.det_FPNHead,FPN_Head

segout:
  function: ptocr.model.segout.det_DB_segout,SegDetector

architectures:
  model_function: ptocr.model.architectures.det_model,DetModel
  loss_function: ptocr.model.architectures.det_model,DetLoss

loss:
  function: ptocr.model.loss.db_loss,DBLoss
  l1_scale: 10
  bce_scale: 1

#optimizer:
#  function: ptocr.optimizer,AdamDecay
#  base_lr: 0.002
#  beta1: 0.9
#  beta2: 0.999

optimizer:
  function: ptocr.optimizer,SGDDecay
  base_lr: 0.002
  momentum: 0.99
  weight_decay: 0.00005

optimizer_decay:
  function: ptocr.optimizer,adjust_learning_rate_poly
  factor: 0.9

#optimizer_decay:
#  function: ptocr.optimizer,adjust_learning_rate
#  schedule: [1,2]
#  gama: 0.1

trainload:
  function: ptocr.dataloader.DetLoad.DBProcess,DBProcessTrain
  train_file: /src/notebooks/chinese_recognize_data/detection/CommonData/train_list.txt
  num_workers: 10
  batch_size: 16

testload:
  function: ptocr.dataloader.DetLoad.DBProcess,DBProcessTest
  test_file: /src/notebooks/detect_text/icdar2015/test_list.txt
  test_gt_path: /src/notebooks/detect_text/icdar2015/ch4_test_gts/
  test_size: 736
  stride: 32
  num_workers: 5
  batch_size: 4

postprocess:
  function: ptocr.postprocess.DBpostprocess,DBPostProcess
  is_poly: False
  thresh: 0.2
  box_thresh: 0.4
  max_candidates: 1000
  unclip_ratio: 2
  min_size: 3

infer:
  model_path: './checkpoint/ag_DB_bb_mobilenet_v3_small_he_DB_Head_bs_16_ep_1200/DB_best.pth.tar'
  path: '/src/notebooks/detect_text/icdar2015/ch4_test_images'
  save_path: './result'
