base:
  gpu_id: '1'
  algorithm: PSE
  pretrained: True
  in_channels: [24, 40, 48, 96]
  inner_channels: 96
  classes: 7
  crop_shape: [640,640]
  shrink_ratio: 0.4
  n_epoch: 1200
  show_step: 5
  checkpoints: ./checkpoint
  restore: False
  restore_file: ./PSE.pth.tar

backbone:
  function: ptocr.model.backbone.det_mobilev3,mobilenet_v3_small

head:
#  function: ptocr.model.head.det_DBHead,DB_Head
#  function: ptocr.model.head.det_FPEM_FFM_Head,FPEM_FFM_Head
  function: ptocr.model.head.det_FPNHead,FPN_Head

segout:
  function: ptocr.model.segout.det_PSE_segout,SegDetector

architectures:
  model_function: ptocr.model.architectures.det_model,DetModel
  loss_function: ptocr.model.architectures.det_model,DetLoss

loss:
  function: ptocr.model.loss.pse_loss,PSELoss
  text_tatio: 0.7

#optimizer:
#  function: ptocr.optimizer,AdamDecay
#  base_lr: 0.002
#  beta1: 0.9
#  beta2: 0.999

optimizer:
  function: ptocr.optimizer,SGDDecay
  base_lr: 0.002
  momentum: 0.99

optimizer_decay:
  function: ptocr.optimizer,adjust_learning_rate_poly
  factor: 0.9

trainload:
  function: ptocr.dataloader.DetLoad.PSEProcess,PSEProcessTrain
  train_file: /src/notebooks/detect_text/icdar2015/train_list.txt
  num_workers: 0
  batch_size: 2

testload:
  function: ptocr.dataloader.DetLoad.PSEProcess,PSEProcessTest
  test_file: /src/notebooks/detect_text/icdar2015/test_list.txt
  test_gt_path: /src/notebooks/detect_text/icdar2015/ch4_test_gts/
  test_size: 2240
  stride: 32
  num_workers: 5
  batch_size: 2

postprocess:
  function: ptocr.postprocess.PSEpostprocess,PSEPostProcess
  is_poly: True
  binary_th: 1
  scale: 1
  min_kernel_area: 5
  min_text_area: 800
  min_score: 0.93
  
infer:
  model_path: './checkpoint/ag_PSE_bb_mobilenet_v3_small_he_FPN_Head_bs_16_ep_1200/PSE_400.pth.tar'
  path: '/src/notebooks/detect_text/icdar2015/ch4_test_images'
  save_path: './result'
  