base:
  gpu_id: '0'
  algorithm: PAN
  pretrained: True
  in_channels: [64, 128, 256, 512]
  inner_channels: 128
  classes: 6
  crop_shape: [640,640]
  shrink_ratio: 0.5
  n_epoch: 601
  show_step: 20
  start_val: 200
  save_epoch: 100
  checkpoints: ./checkpoint
  restore: True
  restore_file: ./checkpoint/ag_PAN_bb_resnet18_he_FPEM_FFM_Head_bs_14_ep_601/PAN_best.pth.tar

backbone:
  function: ptocr.model.backbone.det_resnet_3*3,resnet18

head:
#  function: ptocr.model.head.det_DBHead,DB_Head
  function: ptocr.model.head.det_FPEM_FFM_Head,FPEM_FFM_Head
#  function: ptocr.model.head.det_FPNHead,FPN_Head
segout:
  function: ptocr.model.segout.det_PAN_segout,SegDetector

architectures:
  model_function: ptocr.model.architectures.det_model,DetModel
  loss_function: ptocr.model.architectures.det_model,DetLoss

loss:
  function: ptocr.model.loss.pan_loss,PANLoss
  kernel_rate: 0.5
  agg_dis_rate: 0.25

#optimizer:
#  function: ptocr.optimizer,AdamDecay
#  base_lr: 0.002
#  beta1: 0.9
#  beta2: 0.999

optimizer:
  function: ptocr.optimizer,SGDDecay
  base_lr: 0.001
  momentum: 0.99
  weight_decay: 0.00005

optimizer_decay:
  function: ptocr.optimizer,adjust_learning_rate_poly
  factor: 0.9
  
# optimizer_decay:
#   function: ptocr.optimizer,adjust_learning_rate
#   schedule: [200,400,500]
#   gama: 0.1


trainload:
  function: ptocr.dataloader.DetLoad.PANProcess,PANProcessTrain
  train_file: /src/notebooks/detect_text/icdar2015/train_list.txt
  num_workers: 10
  batch_size: 14

testload:
  function: ptocr.dataloader.DetLoad.PANProcess,PANProcessTest
  test_file: /src/notebooks/detect_text/icdar2015/test_list.txt
  test_gt_path: /src/notebooks/detect_text/icdar2015/ch4_test_gts/
  test_size: 736
  stride: 32
  num_workers: 5
  batch_size: 2

postprocess:
  function: ptocr.postprocess.PANpostprocess,PANPostProcess
  is_poly: False
  bin_th: 1
  scale: 1
  min_kernel_area: 4
  min_text_area: 300
  min_score: 0.90
  dis_thresh: 1
  
infer:
  model_path: './checkpoint/ag_PAN_bb_resnet18_he_FPEM_FFM_Head_bs_14_ep_601/PAN_best.pth.tar'
  path: '/src/notebooks/detect_text/icdar2015/ch4_test_images'
  save_path: './result'