base:
  gpu_id: '0'
  algorithm: CRNN
  pretrained: True
  inchannel: 96
  hiddenchannel: 48
  img_shape: [32,280]
  is_gray: True
  use_conv: False
  use_attention: True
  use_lstm: True
  lstm_num: 2
  classes: 1000
  n_epoch: 1200
  start_val: 15
  show_step: 20
  checkpoints: ./checkpoint
  save_epoch: 100
  show_num: 10
  restore: False
  restore_file : ./DB.pth.tar

backbone:
  function: ptocr.model.backbone.reg_mobilev3,mobilenet_v3_small

head:
  function: ptocr.model.head.rec_CRNNHead,CRNN_Head

architectures:
  model_function: ptocr.model.architectures.rec_model,RecModel
  loss_function: ptocr.model.architectures.rec_model,RecLoss

loss:
  function: ptocr.model.loss.ctc_loss,CTCLoss
  reduction: 'mean' 

optimizer:
 function: ptocr.optimizer,AdamDecay
 base_lr: 0.001
 beta1: 0.9
 beta2: 0.999
 weight_decay: 0.00005

# optimizer:
#   function: ptocr.optimizer,SGDDecay
#   base_lr: 0.002
#   momentum: 0.99
#   weight_decay: 0.00005

optimizer_decay:
  function: ptocr.optimizer,adjust_learning_rate_poly
  factor: 0.9

#optimizer_decay:
#  function: ptocr.optimizer,adjust_learning_rate
#  schedule: [1,2]
#  gama: 0.1

trainload:
  function: ptocr.dataloader.RecLoad.CRNNProcess,CRNNProcessTrain
  train_file: /src/notebooks/fangxuwei_96/crnn-master/train_data/data/train_file/val.txt
  key_file: /src/notebooks/fangxuwei_96/crnn-master/train_data/data/train_file/key.txt
  num_workers: 10
  batch_size: 256

testload:
  function: ptocr.dataloader.RecLoad.CRNNProcess,CRNNProcessTest
  test_file: /src/notebooks/fangxuwei_96/crnn-master/train_data/data/train_file/val.txt
  num_workers: 5
  batch_size: 64
  
label_transform:
  function: ptocr.utils.transform_label,strLabelConverter
  
infer:
  model_path: ''
  path: ''
  save_path: ''
