base:
  gpu_id: '1'
  algorithm: CRNN
  pretrained: False
  inchannel: 512
  hiddenchannel: 128
  img_shape: [32,200]
  is_gray: True
  use_conv: False
  use_attention: False
  use_lstm: False
  lstm_num: 1
  classes: 1000
  n_epoch: 20
  start_val: 0
  show_step: 20
  checkpoints: ./checkpoint
  save_epoch: 1
  show_num: 10
  restore: False
  finetune: False
  restore_file : ./checkpoint/ag_CRNN_bb_rec_crnn_backbone_he_CRNN_Head_bs_256_ep_20_test_center_3/CRNN_best_ori.pth.tar

backbone:
  function: ptocr.model.backbone.reg_resnet_paddle,resnet34

head:
  function: ptocr.model.head.rec_CRNNHead,CRNN_Head

architectures:
  model_function: ptocr.model.architectures.rec_model,RecModel
  loss_function: ptocr.model.architectures.rec_model,RecLoss

loss:
  function: ptocr.model.loss.ctc_loss,CTCLoss
  reduction: 'sum' 
  center_function: ptocr.model.loss.centerloss,CenterLoss
  use_center: False
  center_lr: 0.5
  label_score: 0.95
#   min_score: 0.01
  weight_center: 0.000001
  

optimizer:
 function: ptocr.optimizer,AdamDecay
 base_lr: 0.001
 beta1: 0.9
 beta2: 0.999
 weight_decay: 0.00005

# optimizer:
#   function: ptocr.optimizer,SGDDecay
#   base_lr: 0.002
#   momentum: 0.99
#   weight_decay: 0.00005

# optimizer_decay:
#   function: ptocr.optimizer,adjust_learning_rate_poly
#   factor: 0.9

optimizer_decay:
 function: ptocr.optimizer,adjust_learning_rate
 schedule: [5,10,15]
 gama: 0.1
 
optimizer_decay_center:
 function: ptocr.optimizer,adjust_learning_rate_center
 schedule: [6,10,15]
 gama: 0.1
 
trainload:
  function: ptocr.dataloader.RecLoad.CRNNProcess,CRNNProcessTrain
  train_file: /src/notebooks/fangxuwei_96/crnn-master/train_data/data/train_center/train.txt
  key_file: /src/notebooks/fangxuwei_96/crnn-master/train_data/data/train_center/key.txt
  num_workers: 10
  batch_size: 256

testload:
  function: ptocr.dataloader.RecLoad.CRNNProcess,CRNNProcessTest
  test_file: /src/notebooks/fangxuwei_96/crnn-master/train_data/data/train_center/val.txt
  num_workers: 5
  batch_size: 256

  
label_transform:
  function: ptocr.utils.transform_label,strLabelConverter
  
infer:
  model_path: './checkpoint/ag_CRNN_bb_rec_crnn_backbone_he_CRNN_Head_bs_256_ep_20_test_center_3/CRNN_best.pth.tar'
#   model_path: './checkpoint/ag_CRNN_bb_rec_crnn_backbone_he_CRNN_Head_bs_256_ep_20_no_center/CRNN_best.pth.tar'
  path: '/src/notebooks/fangxuwei_96/crnn-master/train_data/data/gen_data_sim/center_test/default'
  save_path: ''
