base:
  gpu_id: '0,1'
  algorithm: CRNN
  pretrained: False
  inchannel: 512
  hiddenchannel: 128
  img_shape: [32,100]
  is_gray: True
  use_conv: False
  use_attention: False
  use_lstm: True
  lstm_num: 2
  classes: 1000
  n_epoch: 8
  start_val: 0
  show_step: 100
  checkpoints: ./checkpoint
  save_epoch: 1
  show_num: 10
  restore: True
  finetune: True
  restore_file : ./checkpoint/ag_CRNN_bb_resnet34_he_CRNN_Head_bs_256_ep_20_no_channel_timestep_rnn/CRNN_best.pth.tar

backbone:
  function: ptocr.model.backbone.reg_resnet_bd,resnet34

head:
  function: ptocr.model.head.rec_CRNNHead,CRNN_Head

architectures:
  model_function: ptocr.model.architectures.rec_model,RecModel
  loss_function: ptocr.model.architectures.rec_model,RecLoss

loss:
  function: ptocr.model.loss.ctc_loss,CTCLoss
  use_ctc_weight: True
  reduction: 'none' 
  center_function: ptocr.model.loss.centerloss,CenterLoss
  use_center: True
  center_lr: 0.5
  label_score: 0.95
#   min_score: 0.01
  weight_center: 0.001
  

optimizer:
 function: ptocr.optimizer,AdamDecay
 base_lr: 0.001
 beta1: 0.9
 beta2: 0.999
 weight_decay: 0.00005

# optimizer:
#   function: ptocr.optimizer,SGDDecay
#   base_lr: 0.002
#   momentum: 0.99
#   weight_decay: 0.00005

# optimizer_decay:
#   function: ptocr.optimizer,adjust_learning_rate_poly
#   factor: 0.9

optimizer_decay:
 function: ptocr.optimizer,adjust_learning_rate
 schedule: [4,6]
 gama: 0.1
 
optimizer_decay_center:
 function: ptocr.optimizer,adjust_learning_rate_center
 schedule: [4,6]
 gama: 0.1
 
trainload:
  function: ptocr.dataloader.RecLoad.CRNNProcess,CRNNProcessTrainLmdb
  train_file: '/src/notebooks/MyworkData/EnglishCrnnData/train_lmdb/SynthText/'
  key_file: /src/notebooks/MyworkData/EnglishCrnnData/key_new.txt
  bg_path: ./bg_img/
  num_workers: 10
  batch_size: 512

testload:
  function: ptocr.dataloader.RecLoad.CRNNProcess,CRNNProcessTest
  test_file: /src/notebooks/MyworkData/EnglishCrnnData/val_new.txt
  num_workers: 5
  batch_size: 256

  
label_transform:
  function: ptocr.utils.transform_label,strLabelConverter
  
infer:
#   model_path: './checkpoint/ag_CRNN_bb_rec_crnn_backbone_he_CRNN_Head_bs_256_ep_10_synthtext/CRNN_best.pth.tar'
  model_path: './checkpoint/ag_CRNN_bb_resnet34_he_CRNN_Head_bs_512_ep_8_center_loss/CRNN_best.pth.tar'
#   path: '/src/notebooks/MyworkData/EnglishCrnnData/image/2697/6/107_Ramification_62303.jpg'
  path: './english_val_img/SVT/image/'
  save_path: ''
